export const createSeedStudents = () => [
  {
    id: 'student-001',
    student_id: 'STU-2026-001',
    first_name: 'Emma',
    last_name: 'Johnson',
    grade_level: 10,
    class_section: 'A',
    date_of_birth: '2010-04-14',
    gender: 'Female',
    email: 'emma.johnson@school.local',
    phone: '+256700100001',
    parent_name: 'Sarah Johnson',
    parent_phone: '+256700200001',
    parent_email: 'sarah.johnson@family.local',
    address: '12 Lake View Road',
    enrollment_date: '2023-01-09',
    status: 'active',
    gpa: 3.92,
    attendance_rate: 97.4,
    subjects: ['Mathematics', 'English', 'Computer Science', 'Physics'],
    notes: 'Strong academic performance and active in robotics club.',
  },
  {
    id: 'student-002',
    student_id: 'STU-2026-002',
    first_name: 'Liam',
    last_name: 'Carter',
    grade_level: 12,
    class_section: 'B',
    date_of_birth: '2008-11-20',
    gender: 'Male',
    email: 'liam.carter@school.local',
    phone: '+256700100002',
    parent_name: 'Helen Carter',
    parent_phone: '+256700200002',
    parent_email: 'helen.carter@family.local',
    address: '34 Hill Street',
    enrollment_date: '2021-01-11',
    status: 'active',
    gpa: 3.88,
    attendance_rate: 95.1,
    subjects: ['Mathematics', 'Biology', 'Chemistry', 'History'],
    notes: 'Preparing university applications.',
  },
  {
    id: 'student-003',
    student_id: 'STU-2026-003',
    first_name: 'Sophia',
    last_name: 'Kim',
    grade_level: 11,
    class_section: 'A',
    date_of_birth: '2009-06-08',
    gender: 'Female',
    email: 'sophia.kim@school.local',
    phone: '+256700100003',
    parent_name: 'Daniel Kim',
    parent_phone: '+256700200003',
    parent_email: 'daniel.kim@family.local',
    address: '88 Cedar Close',
    enrollment_date: '2022-01-10',
    status: 'active',
    gpa: 3.95,
    attendance_rate: 98.2,
    subjects: ['English', 'Economics', 'Mathematics', 'Art'],
    notes: 'Debate captain and peer tutor.',
  },
  {
    id: 'student-004',
    student_id: 'STU-2026-004',
    first_name: 'Noah',
    last_name: 'Patel',
    grade_level: 9,
    class_section: 'C',
    date_of_birth: '2011-02-02',
    gender: 'Male',
    email: 'noah.patel@school.local',
    phone: '+256700100004',
    parent_name: 'Asha Patel',
    parent_phone: '+256700200004',
    parent_email: 'asha.patel@family.local',
    address: '19 Green Crescent',
    enrollment_date: '2024-01-08',
    status: 'active',
    gpa: 3.41,
    attendance_rate: 89.7,
    subjects: ['English', 'Geography', 'Mathematics', 'Biology'],
    notes: 'Needs occasional support with deadlines.',
  },
  {
    id: 'student-005',
    student_id: 'STU-2026-005',
    first_name: 'Ava',
    last_name: 'Martinez',
    grade_level: 12,
    class_section: 'A',
    date_of_birth: '2008-09-16',
    gender: 'Female',
    email: 'ava.martinez@school.local',
    phone: '+256700100005',
    parent_name: 'Carlos Martinez',
    parent_phone: '+256700200005',
    parent_email: 'carlos.martinez@family.local',
    address: '42 Palm Avenue',
    enrollment_date: '2021-01-11',
    status: 'active',
    gpa: 3.76,
    attendance_rate: 94.3,
    subjects: ['Literature', 'History', 'Art', 'French'],
    notes: 'Student council representative.',
  },
  {
    id: 'student-006',
    student_id: 'STU-2026-006',
    first_name: 'Ethan',
    last_name: 'Brown',
    grade_level: 10,
    class_section: 'B',
    date_of_birth: '2010-01-30',
    gender: 'Male',
    email: 'ethan.brown@school.local',
    phone: '+256700100006',
    parent_name: 'Rachel Brown',
    parent_phone: '+256700200006',
    parent_email: 'rachel.brown@family.local',
    address: '7 Maple Gardens',
    enrollment_date: '2023-01-09',
    status: 'active',
    gpa: 3.12,
    attendance_rate: 91.5,
    subjects: ['Mathematics', 'Physics', 'Computer Science', 'English'],
    notes: 'Performs best in project work.',
  },
  {
    id: 'student-007',
    student_id: 'STU-2026-007',
    first_name: 'Mia',
    last_name: 'Chen',
    grade_level: 9,
    class_section: 'A',
    date_of_birth: '2011-05-12',
    gender: 'Female',
    email: 'mia.chen@school.local',
    phone: '+256700100007',
    parent_name: 'Victor Chen',
    parent_phone: '+256700200007',
    parent_email: 'victor.chen@family.local',
    address: '73 Riverside Court',
    enrollment_date: '2024-01-08',
    status: 'active',
    gpa: 3.67,
    attendance_rate: 96.1,
    subjects: ['Mathematics', 'English', 'Music', 'Biology'],
    notes: 'Excellent classroom participation.',
  },
  {
    id: 'student-008',
    student_id: 'STU-2026-008',
    first_name: 'James',
    last_name: 'Wilson',
    grade_level: 11,
    class_section: 'C',
    date_of_birth: '2009-12-01',
    gender: 'Male',
    email: 'james.wilson@school.local',
    phone: '+256700100008',
    parent_name: 'Grace Wilson',
    parent_phone: '+256700200008',
    parent_email: 'grace.wilson@family.local',
    address: '55 Sunset Lane',
    enrollment_date: '2022-01-10',
    status: 'active',
    gpa: 2.84,
    attendance_rate: 83.4,
    subjects: ['History', 'English', 'Mathematics', 'Physical Education'],
    notes: 'Attendance intervention plan in progress.',
  },
  {
    id: 'student-009',
    student_id: 'STU-2026-009',
    first_name: 'Isabella',
    last_name: 'Davis',
    grade_level: 12,
    class_section: 'C',
    date_of_birth: '2008-03-27',
    gender: 'Female',
    email: 'isabella.davis@school.local',
    phone: '+256700100009',
    parent_name: 'Peter Davis',
    parent_phone: '+256700200009',
    parent_email: 'peter.davis@family.local',
    address: '91 Garden Estate',
    enrollment_date: '2021-01-11',
    status: 'active',
    gpa: 3.58,
    attendance_rate: 92.8,
    subjects: ['Biology', 'Chemistry', 'English', 'Mathematics'],
    notes: 'Interested in medical sciences.',
  },
  {
    id: 'student-010',
    student_id: 'STU-2026-010',
    first_name: 'Benjamin',
    last_name: 'Okello',
    grade_level: 10,
    class_section: 'A',
    date_of_birth: '2010-08-19',
    gender: 'Male',
    email: 'benjamin.okello@school.local',
    phone: '+256700100010',
    parent_name: 'Ruth Okello',
    parent_phone: '+256700200010',
    parent_email: 'ruth.okello@family.local',
    address: '16 Kingsway',
    enrollment_date: '2023-01-09',
    status: 'active',
    gpa: 3.23,
    attendance_rate: 88.6,
    subjects: ['Computer Science', 'Mathematics', 'Geography', 'English'],
    notes: 'Shows strong improvement in coding assignments.',
  },
  {
    id: 'student-011',
    student_id: 'STU-2026-011',
    first_name: 'Charlotte',
    last_name: 'Smith',
    grade_level: 9,
    class_section: 'B',
    date_of_birth: '2011-07-07',
    gender: 'Female',
    email: 'charlotte.smith@school.local',
    phone: '+256700100011',
    parent_name: 'Martha Smith',
    parent_phone: '+256700200011',
    parent_email: 'martha.smith@family.local',
    address: '23 Banyan Drive',
    enrollment_date: '2024-01-08',
    status: 'active',
    gpa: 3.47,
    attendance_rate: 90.2,
    subjects: ['English', 'Mathematics', 'Art', 'French'],
    notes: 'Needs confidence support during presentations.',
  },
  {
    id: 'student-012',
    student_id: 'STU-2026-012',
    first_name: 'Daniel',
    last_name: 'Garcia',
    grade_level: 11,
    class_section: 'B',
    date_of_birth: '2009-10-24',
    gender: 'Male',
    email: 'daniel.garcia@school.local',
    phone: '+256700100012',
    parent_name: 'Nina Garcia',
    parent_phone: '+256700200012',
    parent_email: 'nina.garcia@family.local',
    address: '60 School Lane',
    enrollment_date: '2022-01-10',
    status: 'active',
    gpa: 3.81,
    attendance_rate: 97,
    subjects: ['Physics', 'Computer Science', 'Mathematics', 'English'],
    notes: 'Leads the science fair team.',
  },
  {
    id: 'student-013',
    student_id: 'STU-2026-013',
    first_name: 'Grace',
    last_name: 'Nakitto',
    grade_level: 12,
    class_section: 'B',
    date_of_birth: '2008-06-03',
    gender: 'Female',
    email: 'grace.nakitto@school.local',
    phone: '+256700100013',
    parent_name: 'Moses Nakitto',
    parent_phone: '+256700200013',
    parent_email: 'moses.nakitto@family.local',
    address: '5 Pearl Road',
    enrollment_date: '2021-01-11',
    status: 'active',
    gpa: 3.64,
    attendance_rate: 93.5,
    subjects: ['Economics', 'Literature', 'History', 'English'],
    notes: 'Consistent performance and strong writing skills.',
  },
  {
    id: 'student-014',
    student_id: 'STU-2026-014',
    first_name: 'Michael',
    last_name: 'Thompson',
    grade_level: 10,
    class_section: 'C',
    date_of_birth: '2010-12-09',
    gender: 'Male',
    email: 'michael.thompson@school.local',
    phone: '+256700100014',
    parent_name: 'Angela Thompson',
    parent_phone: '+256700200014',
    parent_email: 'angela.thompson@family.local',
    address: '101 Orchard Park',
    enrollment_date: '2023-01-09',
    status: 'inactive',
    gpa: 2.76,
    attendance_rate: 84.8,
    subjects: ['Mathematics', 'History', 'Physical Education', 'Biology'],
    notes: 'Returned after a prolonged absence.',
  },
  {
    id: 'student-015',
    student_id: 'STU-2026-015',
    first_name: 'Olivia',
    last_name: 'Anderson',
    grade_level: 11,
    class_section: 'A',
    date_of_birth: '2009-04-05',
    gender: 'Female',
    email: 'olivia.anderson@school.local',
    phone: '+256700100015',
    parent_name: 'Simon Anderson',
    parent_phone: '+256700200015',
    parent_email: 'simon.anderson@family.local',
    address: '11 Acacia Avenue',
    enrollment_date: '2022-01-10',
    status: 'active',
    gpa: 3.9,
    attendance_rate: 99.1,
    subjects: ['Computer Science', 'Mathematics', 'Physics', 'English'],
    notes: 'Top performer with excellent attendance.',
  },
];
